### ISSUE TITLE
training issue

### ISSUE THREAD

**Issue by galsk87** [rowanz/neural-motifs#23] opened 2018-09-06 11:41 UTC
Hi I'm trying to train the model with a subset of the predicates thus i'm doing the next change in train_rels.py

intead of inserting train.ind_to_predicates to the rel model im inserting a subset in the next order

rel_list = sample(train.ind_to_predicates, round(0.75*len(train.ind_to_predicates)))

when training i get the next error 

Traceback (most recent call last):
  File "./models/train_rels.py", line 197, in <module>
    rez = train_epoch(epoch)
  File "./models/train_rels.py", line 108, in train_epoch
    tr.append(train_batch(batch, verbose=b % (conf.print_interval*10) == 0)) #b == 0))
  File "./models/train_rels.py", line 140, in train_batch
    result = detector[b]
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 591, in __getitem__
    return self(*batch[0])
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 568, in forward
    ), 1))
RuntimeError: The size of tensor a (38) must match the size of tensor b (51) at non-singleton dimension 1

do you have any idea how to fix this problem or is tehre a different approach i should take in order to train with a subset of the predicates.

**Comment by rowanz** [comment] 2018-09-08 16:08
you would probably need to look this function and change it to match your data. https://github.com/rowanz/neural-motifs/blob/055540821125b750b49f2b5f24de9c835126cebe/dataloaders/visual_genome.py#L365

**Comment by galsk87** [comment] 2018-09-09 11:56
i did the next change in visual_genome:


def load_info(info_file):
    """
    Loads the file containing the visual genome label meanings
    :param info_file: JSON
    :return: ind_to_classes: sorted list of classes
             ind_to_predicates: sorted list of predicates
    """
    info = json.load(open(info_file, 'r'))
    info['label_to_idx']['__background__'] = 0
    info['predicate_to_idx']['__background__'] = 0

    class_to_ind = info['label_to_idx']
    predicate_to_ind = info['predicate_to_idx']
    ind_to_classes = sorted(class_to_ind, key=lambda k: class_to_ind[k])
    ind_to_predicates = sorted(predicate_to_ind, key=lambda k: predicate_to_ind[k])
    ind_to_predicates = sample(ind_to_predicates, round(0.75 * len(ind_to_predicates)))
    return ind_to_classes, ind_to_predicates


and got the next error:

  File "/home/sgalk87/neural-motifs/lib/get_dataset_counts.py", line 38, in get_counts
    fg_matrix[o1, o2, gtr] += 1
IndexError: index 50 is out of bounds for axis 2 with size 38

**Comment by rowanz** [comment] 2018-09-10 22:27
You might also have to change the other downloaded scene graph files. Anyways, I'm going to close this because It's not something I officially want to support: this repository is just for reproducing my paper results (using my exact preprocessing steps).

**Closed by rowanz** 2018-09-10 22:27 UTC
